# Generated by Django 5.1.5 on 2026-01-28 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('superadmin', 'Super Administrador'), ('medico', 'Médico'), ('enfermera', 'Enfermera')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medico', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicos.medico')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
