# Generated by Django 5.1.5 on 2026-01-22 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atenciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(editable=False, max_length=20, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], max_length=20)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('atencion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='atenciones.atencion')),
            ],
        ),
    ]
