# Generated by Django 5.1.5 on 2025-09-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cedula',
            field=models.CharField(default='0000000000', max_length=10, unique=True),
        ),
    ]
