# Generated by Django 5.1.5 on 2026-01-20 00:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_paciente_cedula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_registro',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cedula',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener exactamente 10 dígitos numéricos', regex='^\\d{10}$')]),
        ),
    ]
